apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.giropopsSenha.labels.app }}
  name: {{ .Values.giropopsSenha.name }} # valor declarado no values.yaml
spec:
  replicas: {{ .Values.giropopsSenha.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.giropopsSenha.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.giropopsSenha.labels.app }}
    spec:
      containers:
      - image: {{ .Values.giropopsSenha.image }} # valor declarado no values.yaml
        name: giropops-senhas
        ports:
        - containerPort: {{ .Values.giropopsSenha.service.port }}
        imagePullPolicy: Always