{{- range $component, $config := .Values.services }}
  {{- range $port := $config.ports  }} # instrução para pecorrer as informações de port de values.yaml.
apiVersion: v1
kind: Service
metadata:
  name: {{ $component }}-{{ $port.name }}
  labels: 
    app: {{ $config.labels.app }}
spec:
  type: {{ $port.serviceType }}
  ports:
  - port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: TCP
    name: {{ $port.name }}
    {{- if eq $port.serviceType "NodePort" }}
    nodePort: {{ .NodePort }}
    {{- end }} 
  selector:
    app: {{ $config.labels.app }}
---
{{- end }}
{{- end }}