apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: {{ .Values.redis.name }} # valor declarado no values.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: {{ .Values.redis.image }} # valor declarado no values.yaml
        name: redis
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"