apiVersion: v1
kind: Secret 
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRo
    IjogImJIVmpmpZWE1qTWpBeU5BPT0iCgkJfQoJfQp9
