apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    name: meu-pod
spec:
  containers:
  - name: meu-container
    image: lucasjct/docker101tutorial:latest
  imagePullSecrets:
    - name: dockerhub-secret
