apiVersion: v1
data:
  nginx.conf: | 
    events {}

    http{
      server{
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/tls/certificado.crt;
        ssl_certificate_key /etc/nginx/tls/chave-privada.key;
        
        location / {
          return 200 'ola terraqueos e extraterrestres"\n';
          add_header Content-Tyoe text/plain;
        } 
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: zora-system