apiVersion: v1
kind: Service 
metadata:
  name: nginx-nodeport
  labels:
    app: nginx # recebe a label utilizda no deployment.
    env: dev
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 32000
  type: NodePort # tipo do service: NodePort